package entities;

//
// This file was generated by the JPA Modeler
//

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;

@Entity
public class Respostas_Dadas implements Serializable {

    @Column(unique = true)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id_respostas_dadas;

    @ManyToOne(targetEntity = Utilizador_Inquerito.class)
    private Utilizador_Inquerito utilizador_Inquerito;

    public Respostas_Dadas() {

    }

    public Long getId_respostas_dadas() {
        return this.id_respostas_dadas;
    }

    public void setId_respostas_dadas(Long id_respostas_dadas) {
        this.id_respostas_dadas = id_respostas_dadas;
    }

    public Utilizador_Inquerito getUtilizador_Inquerito() {
        return this.utilizador_Inquerito;
    }

    public void setUtilizador_Inquerito(Utilizador_Inquerito utilizador_Inquerito) {
        this.utilizador_Inquerito = utilizador_Inquerito;
    }
}
