package entities;

//
// This file was generated by the JPA Modeler
//

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;

@Entity
public class Respostas_Possiveis implements Serializable {

    @Basic
    private String texto;

    @Column(unique = true)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id_respostas_possiveis;

    @ManyToOne(targetEntity = Questao.class)
    private Questao questao;

    public Respostas_Possiveis() {

    }

    public String getTexto() {
        return this.texto;
    }

    public void setTexto(String texto) {
        this.texto = texto;
    }

    public Long getId_respostas_possiveis() {
        return this.id_respostas_possiveis;
    }

    public void setId_respostas_possiveis(Long id_respostas_possiveis) {
        this.id_respostas_possiveis = id_respostas_possiveis;
    }

    public Questao getQuestao() {
        return this.questao;
    }

    public void setQuestao(Questao questao) {
        this.questao = questao;
    }
}
