package entities;

//
// This file was generated by the JPA Modeler
//

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;

@Entity
public class Utilizador implements Serializable {

    @Basic
    private Integer telefone;

    @Basic
    private String password;

    @Basic
    private String nome;

    @ManyToOne(targetEntity = Tipo_Utilizador.class)
    private Tipo_Utilizador tipo_Utilizador;

    @Column(unique = true)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id_utilizador;

    @Basic
    private String email;

    @Basic
    private String username;

    public Utilizador() {

    }

    public Integer getTelefone() {
        return this.telefone;
    }

    public void setTelefone(Integer telefone) {
        this.telefone = telefone;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public Tipo_Utilizador getTipo_Utilizador() {
        return this.tipo_Utilizador;
    }

    public void setTipo_Utilizador(Tipo_Utilizador tipo_Utilizador) {
        this.tipo_Utilizador = tipo_Utilizador;
    }

    public Long getId_utilizador() {
        return this.id_utilizador;
    }

    public void setId_utilizador(Long id_utilizador) {
        this.id_utilizador = id_utilizador;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }
}
